# Generated by Django 3.2.13 on 2022-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('traffic', models.IntegerField(default=0)),
                ('d1', models.CharField(max_length=50)),
                ('d1_num', models.IntegerField(default=0)),
                ('d2', models.CharField(max_length=50)),
                ('d2_num', models.IntegerField(default=0)),
                ('d3', models.CharField(max_length=50)),
                ('d3_num', models.IntegerField(default=0)),
                ('d4', models.CharField(max_length=50)),
                ('d4_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('traffic', models.IntegerField(blank=True, default=0)),
                ('a1', models.CharField(blank=True, max_length=50)),
                ('a1_num', models.IntegerField(blank=True, default=0)),
                ('a2', models.CharField(blank=True, max_length=50)),
                ('a2_num', models.IntegerField(blank=True, default=0)),
                ('a3', models.CharField(blank=True, max_length=50)),
                ('a3_num', models.IntegerField(blank=True, default=0)),
                ('a4', models.CharField(blank=True, max_length=50)),
                ('a4_num', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
